export const initialEvento = {
  nombre_evento: '',
  tipo: '',
  thumb: '',
  equipo: '',
  inicio_inscripcion: '',
  fin_inscripcion: '',
  organizador: '',
  lugar: '',
  hora: '',
  email: '',
  telefono: '',
  descripcion: '',
  requisito: '',
  reglas: '',
  integrantes: '',
  detalle: '',
  afiche: '',
  premio: '',
  contenido: '',
  invitado: ''
}
