export const initialEvento = {
  nombre_evento: '',
  tipoEvento_id:1,
  thumb: '',
  equipo: '',
  inicio_inscripcion: '',
  fin_inscripcion: '',
  hora_inicio_inscripcion:'',
  hora_fin_inscripcion:'',
  inicio_actividades:'',
  fin_actividades:'',
  hora_inicio_actividades:'',
  hora_fin_actividades:'',
  organizador: '',
  lugar: '',
  hora: '',
  email: '',
  telefono: '',
  descripcion: '',
  requisito: '',
  reglas: '',
  integrantes: '',
  detalle: '',
  afiche: '',
  premio: '',
  contenido: '',
  invitado: ''
}
